
DROP TABLE  NARUDZBA; 
DROP TABLE SURADNIK ;
DROP TABLE ARTIKL_POSL_DOBAVLJAC;
DROP TABLE  ARTPOSL;
DROP TABLE  DOBAVLJAC;
DROP TABLE  RADNIK;
DROP TABLE  POSLOVNICA; 
DROP TABLE  VODITELJ;  
DROP TABLE  LOKACIJA;  
DROP TABLE  GRAD; 
DROP TABLE  OSTALO; 
DROP TABLE  ALKOHOLNA;
DROP TABLE BEZALKOHOLNA ;
DROP TABLE  ARTIKL; 


CREATE TABLE ARTIKL (
    ARTIKL_ID INT PRIMARY KEY,
    PROIZVODAC VARCHAR(50) NOT NULL,
    CIJENA NUMERIC(4,2) NOT NULL,
    VRSTA_PAKIRANJA VARCHAR(100) NOT NULL
);

CREATE TABLE BEZALKOHOLNA (
    ARTIKL_ID INT PRIMARY KEY,
    SECER NUMERIC(6,2), 
    KOFEIN NUMERIC(6,2),
    CONSTRAINT ARTIKL_BA_FK FOREIGN KEY (ARTIKL_ID) REFERENCES ARTIKL(ARTIKL_ID)
);

CREATE TABLE ALKOHOLNA (
    ARTIKL_ID INT PRIMARY KEY,
    ALKOHOL NUMERIC(4,2) NOT NULL, 
    CONSTRAINT ARTIKL_A_FK FOREIGN KEY (ARTIKL_ID) REFERENCES ARTIKL(ARTIKL_ID)
);

CREATE TABLE OSTALO (
    ARTIKL_ID INT PRIMARY KEY,
    CONSTRAINT ARTIKL_FK FOREIGN KEY (ARTIKL_ID) REFERENCES ARTIKL(ARTIKL_ID)
);

CREATE TABLE GRAD(
    GRAD_ID INT PRIMARY KEY,
    NAZIV VARCHAR(50) NOT NULL
);

CREATE TABLE LOKACIJA(
    LOKACIJA_ID INT PRIMARY KEY,
    ADRESA VARCHAR(50) NOT NULL,
    KUCNI_BR INT NOT NULL,
    GRAD_ID INT,
    FOREIGN KEY (GRAD_ID) REFERENCES GRAD(GRAD_ID)
);    

CREATE TABLE VODITELJ(
    OIB INT PRIMARY KEY,
    IME VARCHAR(50) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    PLACA NUMERIC(8,2) NOT NULL,
    IBAN VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE POSLOVNICA(
    POSLOVNICA_ID INT PRIMARY KEY,
    OIB INT NOT NULL,
    LOKACIJA_ID INT NOT NULL,
    FOREIGN KEY (LOKACIJA_ID) REFERENCES LOKACIJA(LOKACIJA_ID),
    FOREIGN KEY (OIB) REFERENCES VODITELJ(OIB)
);

CREATE TABLE RADNIK(
    OIB INT PRIMARY KEY,
    IME VARCHAR(50) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    PLACA NUMERIC(8,2) NOT NULL,
    IBAN VARCHAR(20) NOT NULL,
    POSLOVNICA_ID INT,
    FOREIGN KEY (POSLOVNICA_ID) REFERENCES POSLOVNICA(POSLOVNICA_ID)
);    

CREATE TABLE DOBAVLJAC(
    DOBAVLJAC_ID INT PRIMARY KEY,
    NAZIV VARCHAR(50) NOT NULL,
    BROJ_RACUNA VARCHAR(50) NOT NULL,
    LOKACIJA_ID INT,
    FOREIGN KEY (LOKACIJA_ID) REFERENCES LOKACIJA(LOKACIJA_ID)
);

CREATE TABLE ARTPOSL (
    ARTPOSL_ID INT PRIMARY KEY,
    KOLICINA INT,
    DOBAVLJAC_ID INT,
    ARTIKL_ID INT,
    FOREIGN KEY (DOBAVLJAC_ID) REFERENCES DOBAVLJAC (DOBAVLJAC_ID),
    FOREIGN KEY (ARTIKL_ID) REFERENCES ARTIKL (ARTIKL_ID)
);

CREATE TABLE ARTIKL_POSL_DOBAVLJAC (
    APD_ID INT PRIMARY KEY,
    ARTPOSL_ID INT,
    POSLOVNICA_ID INT,
    FOREIGN KEY (ARTPOSL_ID) REFERENCES ARTPOSL(ARTPOSL_ID),
    FOREIGN KEY (POSLOVNICA_ID) REFERENCES POSLOVNICA(POSLOVNICA_ID)
);

CREATE TABLE SURADNIK(
    SURADNIK_ID INT PRIMARY KEY,
    NAZIV VARCHAR(50) NOT NULL,
    LOKACIJA_ID INT,
    FOREIGN KEY (LOKACIJA_ID) REFERENCES LOKACIJA(LOKACIJA_ID)
);

CREATE TABLE NARUDZBA(
    NARUDZBA_ID INT PRIMARY KEY,
    DATUM DATE,
    POSLOVNICA_ID INT,
    SURADNIK_ID INT,
    FOREIGN KEY (POSLOVNICA_ID) REFERENCES POSLOVNICA(POSLOVNICA_ID),
    FOREIGN KEY (SURADNIK_ID) REFERENCES SURADNIK(SURADNIK_ID)
);