ALTER SESSION SET NLS_DATE_FORMAT ='dd-mm-yyyy'; 

--<<<<<<<<<<<<|5 JEDNOSTAVNIH UPITA|>>>>>>>>>>>>>--

--ISPISATI NAZIVE SVIH SURADNIKA
SELECT NAZIV FROM SURADNIK;
--ISPISATI SVE VODITELJE  OIB IBAN I NJIHOVE PLACE
SELECT OIB,IBAN, PLACA FROM VODITELJ;
--ISPISATI IMENA I PREZIMENA VODITELJA
SELECT IME||' '||PREZIME AS "ime_prezime voditelja" FROM VODITELJ;
--ISPISITE SVE NARUDZBE NEKOG ODREDENOG DATUMA
SELECT * FROM NARUDZBA
WHERE DATUM = '27-07-2023';
--SVI ARTIKLI KOJIMA JE CIJENA > 5 EURA
SELECT * FROM ARTIKL 
WHERE CIJENA >5.0;

--<<<<<<<<<<<<|5 UPITA NAD VISE TABLICA|>>>>>>>>>>>>>--

--SVE POSLOVNICE U OSIJEKU
SELECT LOKACIJA.ADRESA,LOKACIJA.KUCNI_BR,GRAD.NAZIV, POSLOVNICA.POSLOVNICA_ID FROM POSLOVNICA
JOIN LOKACIJA ON POSLOVNICA.LOKACIJA_ID = LOKACIJA.LOKACIJA_ID
JOIN GRAD ON GRAD.GRAD_ID = LOKACIJA.GRAD_ID
WHERE GRAD.NAZIV = 'OSIJEK';
--KOLICINA COCA-COLE U DRZUGOJ POSLOVNICI
SELECT ARTIKL.PROIZVODAC,ARTIKL.VRSTA_PAKIRANJA , ARTPOSL.KOLICINA FROM ARTPOSL
JOIN ARTIKL_POSL_DOBAVLJAC ON ARTPOSL.ARTPOSL_ID = ARTIKL_POSL_DOBAVLJAC.ARTPOSL_ID
JOIN POSLOVNICA ON POSLOVNICA.POSLOVNICA_ID = ARTIKL_POSL_DOBAVLJAC.POSLOVNICA_ID
JOIN ARTIKL ON ARTIKL.ARTIKL_ID= ARTPOSL.ARTIKL_ID
WHERE ARTIKL.PROIZVODAC = 'coca cola' and POSLOVNICA.POSLOVNICA_ID = 2;
-- NAZIV DOBAVLJACA KOJI DOVOZI OSJECKO PIVO
SELECT DISTINCT NAZIV FROM DOBAVLJAC
JOIN ARTPOSL ON ARTPOSL.DOBAVLJAC_ID = DOBAVLJAC.DOBAVLJAC_ID
JOIN ARTIKL ON ARTIKL.ARTIKL_ID  = ARTPOSL.ARTIKL_ID
WHERE ARTIKL.PROIZVODAC = 'osjecko';
-- ISPISATI E-MAILOVE SVIH VODITELJA CIJE POSLOVNICE IMAJU ALKOHOLNI ARTIKL
SELECT DISTINCT EMAIL FROM VODITELJ
JOIN POSLOVNICA ON POSLOVNICA.OIB = VODITELJ.OIB
JOIN ARTIKL_POSL_DOBAVLJAC ON POSLOVNICA.POSLOVNICA_ID = ARTIKL_POSL_DOBAVLJAC.POSLOVNICA_ID
JOIN ARTPOSL ON ARTPOSL.ARTPOSL_ID = ARTIKL_POSL_DOBAVLJAC.ARTPOSL_ID
JOIN ARTIKL ON ARTIKL.ARTIKL_ID = ARTPOSL.ARTIKL_ID
JOIN ALKOHOLNA ON ALKOHOLNA.ARTIKL_ID = ARTIKL.ARTIKL_ID
WHERE ALKOHOLNA.ARTIKL_ID IS NOT NULL;
-- SVE NARUDZBE CIJI JE SURADNIK IZ ZAHAROVE ULICE
SELECT SURADNIK.NAZIV, NARUDZBA.DATUM, NARUDZBA.NARUDZBA_ID FROM NARUDZBA
JOIN SURADNIK ON SURADNIK.SURADNIK_ID = NARUDZBA.SURADNIK_ID
JOIN LOKACIJA ON LOKACIJA.LOKACIJA_ID = SURADNIK.LOKACIJA_ID
WHERE LOKACIJA.ADRESA ='Zaharova ulica';

--<<<<<<<<<<<<|5 UPITA S AGREGIRAJUCOM FUNKCIJOM|>>>>>>>>>>>>>--

-- ISPIS AVG PLACU RADNIKA
SELECT ROUND(AVG(PLACA),2)  AS "AVG PLACA" FROM RADNIK;
-- ISPISI BROJ DOBAVLJACA ZA 1 POSLOVNICU
SELECT COUNT(DOBAVLJAC.DOBAVLJAC_ID) AS "UKUPAN BROJ DOBAVLJACA"FROM DOBAVLJAC
JOIN ARTPOSL ON DOBAVLJAC.DOBAVLJAC_ID = ARTPOSL.DOBAVLJAC_ID
JOIN ARTIKL_POSL_DOBAVLJAC ON ARTIKL_POSL_DOBAVLJAC.ARTPOSL_ID = ARTPOSL.ARTPOSL_ID
JOIN POSLOVNICA ON POSLOVNICA.POSLOVNICA_ID = ARTIKL_POSL_DOBAVLJAC.POSLOVNICA_ID
WHERE POSLOVNICA.POSLOVNICA_ID = 1;
-- ISPIS UKUPNU KOLICINU BEZALKOHOLNIH PICA U POSLOVNICI 5
SELECT SUM(ARTPOSL.KOLICINA) AS "UKUPNO BOCA" FROM ARTPOSL
JOIN ARTIKL_POSL_DOBAVLJAC ON ARTIKL_POSL_DOBAVLJAC.ARTPOSL_ID = ARTPOSL.ARTPOSL_ID    
JOIN POSLOVNICA ON POSLOVNICA.POSLOVNICA_ID = ARTIKL_POSL_DOBAVLJAC.POSLOVNICA_ID
JOIN BEZALKOHOLNA ON BEZALKOHOLNA.ARTIKL_ID = ARTPOSL.ARTIKL_ID
WHERE BEZALKOHOLNA.ARTIKL_ID IS NOT NULL AND POSLOVNICA.POSLOVNICA_ID = 5;
-- ISPISI ARTIKL S NAJMANJOM CIJENOM
SELECT MIN(ARTIKL.CIJENA) AS "MIN BUDGET" FROM ARTIKL;
-- ISPISI VODITELJA S NAJVECOM PLACOM
SELECT MAX(VODITELJ.PLACA) AS "NAJVECA PLACA VODITELJA" FROM voditelj;

--<<<<<<<<<<<<|5 SLOZENIH UPITA|>>>>>>>>>>>>>--

--ISPISI SVE RADNIKE KOJI IMAJU MANJU PLACU OD PROSIJECNE PLACE RADNIKA
SELECT RADNIK.OIB, RADNIK.IME, RADNIK.PREZIME , RADNIK.PLACA FROM RADNIK
WHERE RADNIK.PLACA<(SELECT ROUND(AVG(PLACA),2) FROM RADNIK);
--ISPISI SVE ARTIKLE KOJI SE NE DOSTAVLJAJU U 3. POSLOVNICU
SELECT ARTIKL.ARTIKL_ID ,  ARTIKL.PROIZVODAC FROM ARTIKL
WHERE ARTIKL.ARTIKL_ID NOT IN 
(SELECT ARTIKL_ID FROM ARTPOSL 
JOIN ARTIKL_POSL_DOBAVLJAC ON ARTIKL_POSL_DOBAVLJAC.ARTPOSL_ID = ARTPOSL.ARTPOSL_ID
JOIN POSLOVNICA ON POSLOVNICA.POSLOVNICA_ID = ARTIKL_POSL_DOBAVLJAC.POSLOVNICA_ID
WHERE ARTPOSL.ARTIKL_ID IS NOT NULL AND  POSLOVNICA.POSLOVNICA_ID =3);
--ISPISI SVE DOBAVLJACE I SURADNIKE IZ OSIJEKA
SELECT DOBAVLJAC_ID, DOBAVLJAC.NAZIV AS "DOBAVLJAC", 'Dobavljac' AS "OPIS"
FROM DOBAVLJAC
JOIN LOKACIJA ON LOKACIJA.LOKACIJA_ID = DOBAVLJAC.LOKACIJA_ID
JOIN GRAD ON GRAD.GRAD_ID = LOKACIJA.GRAD_ID
WHERE GRAD.NAZIV = 'OSIJEK'
UNION
SELECT SURADNIK_ID, SURADNIK.NAZIV AS "SURADNIK", 'Suradnik' AS "OPIS"
FROM SURADNIK
JOIN LOKACIJA ON SURADNIK.LOKACIJA_ID = LOKACIJA.LOKACIJA_ID
JOIN GRAD ON GRAD.GRAD_ID = LOKACIJA.GRAD_ID
WHERE GRAD.NAZIV = 'OSIJEK';
--ISPISI SVE DOBAVLJACE KOJI NE DOVOZE ALKOHOL
SELECT DOBAVLJAC.DOBAVLJAC_ID, DOBAVLJAC.NAZIV FROM DOBAVLJAC
MINUS
SELECT DOBAVLJAC.DOBAVLJAC_ID,DOBAVLJAC.NAZIV FROM DOBAVLJAC
JOIN ARTPOSL ON DOBAVLJAC.DOBAVLJAC_ID = ARTPOSL.DOBAVLJAC_ID
JOIN ALKOHOLNA ON ALKOHOLNA.ARTIKL_ID = ARTPOSL.ARTIKL_ID
WHERE ALKOHOLNA.ARTIKL_ID IS NOT NULL;
--ISPISI SVE RADNIKE OSIM ONIH KOJI IMAJU 5 NAJVECIH PLACA NE UKLJUCUJUCI VODITELJE
SELECT RADNIK.OIB, RADNIK.IME || ' ' || RADNIK.PREZIME AS "ime_prezime", RADNIK.PLACA FROM RADNIK
WHERE RADNIK.PLACA NOT IN (
  SELECT RADNIK.PLACA
  FROM RADNIK
  ORDER BY RADNIK.PLACA DESC 
  FETCH FIRST 5 ROWS ONLY
) ORDER BY RADNIK.PLACA DESC;